version: "3.4"
networks:
  constr-sw-2022-2:
volumes:
  keycloak-data:
    external: false
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=a12345678
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    networks:
      - constr-sw-2022-2
  backend:
    container_name: backend
    build: .
    image: constr-soft-2022-2/backend-api:v1
    ports:
      - 3000:3000
    networks:
      - constr-sw-2022-2
      