version: "3.4"
networks:
  constr-sw-2022-2:
volumes:
  keycloak-data:
    external: false
  mongodb-data:
    external: false
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:16.1.1
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=a12345678
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    networks:
      - constr-sw-2022-2
  keycloak_api:
    container_name: keycloak_api
    build: ./keycloak
    ports:
      - 3000:3000
    environment:
      - KEYCLOAK_HOST=host.docker.internal
      - KEYCLOAK_PORT=8080
      - API_PORT=3000
      - REALM_NAME=constr-sw-2022-2
      - CLIENT_SECRET=GQ3WPDySv8xn6JFPVkrJiQRYjaz5zZFq
    networks:
      - constr-sw-2022-2
    depends_on:
      - keycloak
  mongodb:
    container_name: mongodb
    image: mongo:6.0.2
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=a12345678
    volumes:
      - mongodb-data:/data/mongodb
    networks:
      - constr-sw-2022-2
  buildings_classrooms:
    container_name: buildings_classrooms
    build: ./buildings-classrooms
    ports:
      - 8081:8081
    environment:
      - KEYCLOAK_API_HOST=host.docker.internal
      - KEYCLOAK_API_PORT=3000
      - MONGODB_HOST=host.docker.internal
      - MONGODB_PORT=27017
      - MONGODB_USER=admin
      - MONGODB_PASSWORD=a12345678
      - API_PORT=8081
    networks:
      - constr-sw-2022-2
    depends_on:
      - keycloak_api
      - mongodb